
export const NOTIFICATION_ROLES = [
  "ADMIN",
  "MANAGER",
  "MEMBER",
  "PACKAGING",
];

export const NOTIFICATION_TYPES = [
  // ACCOUNT
  "REGISTRATION",
  "ACCOUNT_ACTIVATED",
  "ACCOUNT_BLOCKED",
  "ACCOUNT_UNBLOCKED",
  "PROFILE_UPDATED",
  "MOBILE_UPDATED",
  "EMAIL_UPDATED",
  "PASSWORD_CHANGED",
  "PASSWORD_RESET",
  "NEW_LOGIN",

  // MEMBERSHIP
  "MEMBERSHIP_PAYMENT",
  "MEMBERSHIP_ACTIVATED",
  "MEMBERSHIP_RENEWED",
  "MEMBERSHIP_SP_CREDITED",
  "MEMBERSHIP_STATUS_CHANGED",

  // WALLET
  "WALLET_CREDITED",
  "WALLET_DEBITED",
  "WALLET_UPDATED",
  "WALLET_TRANSACTION",
  "WALLET_REVERSED",
  "WITHDRAWAL_REQUESTED",
  "WITHDRAWAL_APPROVED",
  "WITHDRAWAL_REJECTED",
  "WITHDRAWAL_COMPLETED",

  // COMMISSION
  "COMMISSION_RECEIVED",
  "COMMISSION_CREDITED",
  "COMMISSION_UPDATED",
  "COMMISSION_REVERSED",
  "COMMISSION_ADJUSTED",

  // SELLING POINTS
  "SP_RECEIVED",
  "SP_UPDATED",
  "SP_ADJUSTED",
  "DISCOUNT_LEVEL_CHANGED",
  "DISCOUNT_RECEIVED",
  "SUPERVISOR_TARGET_REACHED",
  "SUPERVISOR_PROMOTED",
  "SUPERVISOR_BONUS",

  // PRODUCTS
  "PRODUCT_ADDED",
  "PRODUCT_UPDATED",
  "PRODUCT_PRICE_UPDATED",
  "PRODUCT_DISCOUNT_UPDATED",
  "PRODUCT_BACK_IN_STOCK",
  "PRODUCT_LOW_STOCK",
  "PRODUCT_OUT_OF_STOCK",

  // ORDERS
  "ORDER_CREATED",
  "ORDER_PAYMENT_SUCCESS",
  "ORDER_CONFIRMED",
  "ORDER_ASSIGNED",
  "ORDER_PACKED",
  "ORDER_SHIPPED",
  "ORDER_OUT_FOR_DELIVERY",
  "ORDER_DELIVERED",
  "ORDER_CANCELLED",
  "ORDER_FAILED",
  "ORDER_UPDATED",
  "ORDER_ITEM_UPDATED",
  "ORDER_TRACKING_UPDATED",
  "ORDER_RETURNED",
  "ORDER_REFUND",

  // PACKAGING
  "PACKAGING_ASSIGNED",
  "PACKAGING_ACCEPTED",
  "PACKAGING_STARTED",
  "PACKAGING_COMPLETED",
  "PACKAGE_READY",
  "PACKAGE_DISPATCHED",
  "PACKAGING_DELAYED",
  "PACKAGING_ISSUE",
  "PACKAGING_REASSIGNED",

  // KYC
  "KYC_SUBMITTED",
  "KYC_DOCUMENT_UPLOADED",
  "KYC_DOCUMENT_UPDATED",
  "KYC_APPROVED",
  "KYC_REJECTED",
  "KYC_REUPLOAD_REQUIRED",
  "KYC_COMPLETED",

  // REFERRAL
  "NEW_REFERRAL",
  "REFERRAL_REGISTERED",
  "REFERRAL_ACTIVATED",
  "REFERRAL_MEMBERSHIP_ACTIVATED",
  "TEAM_MEMBER_STATUS_CHANGED",

  // MANAGER
  "MANAGER_NEW_ORDER",
  "MANAGER_ORDER_ASSIGNED",
  "MANAGER_NEW_MEMBER",
  "MANAGER_PRODUCT_UPDATED",
  "MANAGER_STOCK_ALERT",
  "MANAGER_PACKAGING_UPDATE",
  "MANAGER_SALES_UPDATE",
  "MANAGER_ANNOUNCEMENT",
  "MANAGER_ACCOUNT_STATUS",

  // PACKAGING ACCOUNT
  "PACKAGING_ACCOUNT_CREATED",
  "PACKAGING_ACCOUNT_UPDATED",
  "PACKAGING_TASK_ASSIGNED",

  // ADMIN
  "ADMIN_NEW_REGISTRATION",
  "ADMIN_PAYMENT_RECEIVED",
  "ADMIN_WITHDRAWAL_REQUEST",
  "ADMIN_KYC_PENDING",
  "ADMIN_SYSTEM_ALERT",

  // GENERAL
  "ANNOUNCEMENT",
  "SYSTEM_ALERT",
];

export const NOTIFICATION_PRIORITIES = [
  "LOW",
  "NORMAL",
  "HIGH",
  "URGENT",
];