const ORDER_STATUSES = [
  "PLACED",
  "CONFIRMED",
  "PACKING",
  "PACKED",
  "READY_FOR_DISPATCH",
  "SHIPPED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "CANCELLED",
];

module.exports = ORDER_STATUSES;